[bumpver]
current_version = "1.1.4"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"save_to_zotero/save_to_zotero.py" = [
    '    VERSION: str = "{version}"',
]

"setup.py" = [
    'version="{version}"',
]
